import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import StoreProvider from "@/store/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import Layout from "@/components/layouts/RootLayout";
import TanstackQuery from "@/lib/TanstackQuery";
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" id="dark">
            <body className={inter.className}>
                <StoreProvider>
                    <TanstackQuery>
                        <Layout>{children}</Layout>
                    </TanstackQuery>
                </StoreProvider>
            </body>
        </html>
    );
}
