import SideNavbar from "@/components/partials/navbar/sideNavBar/SideNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <header className="
            z-40
            xl:pl-64 transition-[padding] duration-200
            ">
                <nav>top bar</nav>
            </header>
            <SideNavbar/>
            <main className="
            z-0
            xl:pl-64 transition-[padding] duration-200
            ">{children}</main>
        </>
    );
}
